name: flutter_plugin_generator
description: Flutter Plugin generator generates a plugin implementation for you.
version: 0.0.9
author: Júlio Cesar Bueno Cotta <juliocbcotta@gmail.com>
homepage: https://github.com/BugsBunnyBR/plugin_gen.flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  build: ^1.1.5
  source_gen: ^0.9.4
  analyzer: '>=0.37.1 <0.38.0'
  flutter_plugin_annotations: ^0.0.9

dev_dependencies:
  test: ^1.6.5
  build_test: ^0.10.8
  build_runner: ^1.6.5
