name: flutter_plugin_annotations
description: A library with the annotations for flutter_plugin_generator.
version: 0.0.1
author: Júlio Cesar Bueno Cotta <juliocbcotta@gmail.com>
homepage: https://github.com/BugsBunnyBR/plugin_gen.flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
