name: flutter_plugin_annotations
description: A library with the annotations for flutter_plugin_generator.
version: 0.0.4
author: Júlio Cesar Bueno Cotta <juliocbcotta@gmail.com>
homepage: https://github.com/BugsBunnyBR/plugin_gen.flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.6.5